/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/*  CS 532 - Project 2 (Spring 2018)
*   1. Shriram Suryawanshi
*   2. Vinen Furtado
*/

package minipods;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import oracle.jdbc.pool.OracleDataSource;

/**
 *
 * @author shree
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public String user;
    public String pass;
    Connection conn;

    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() { // @@ autogenerated GUI code has been removed to reduce code size in the hard copy      }// </editor-fold>                        


    private void B_Login_LoginActionPerformed(java.awt.event.ActionEvent evt) {                                              

        if (T_Username.getText().equals("")) {
            L_Error_Login.setText("Please enter username!");
            L_Error_Login.setVisible(true);
        } else {

            // @@ - perform login operation
            try {

                this.user = T_Username.getText();
                this.pass = new String(T_Password.getPassword());

                // @@ - connect to DB
                OracleDataSource ds = new oracle.jdbc.pool.OracleDataSource();
                //ds.setURL("jdbc:oracle:thin:@localhost:1521:orcl");
                //Connection conn = ds.getConnection("shree", "shree");
                ds.setURL("jdbc:oracle:thin:@castor.cc.binghamton.edu:1521:ACAD111");
                conn = ds.getConnection(user, pass);

                // @@ - login successful, move to Home screen
                if (!conn.isClosed()) {
                    setVisible(false);
                    new Home(user, pass).setVisible(true);
                }

                conn.close();

            } catch (SQLException ex) {
                // @@ - show errors on Login Window
                L_Error_Login.setText(ex.toString());
                L_Error_Login.setVisible(true);
                
                // @shree - handling too many session error by killing conn
                try {
                    conn.close();
                } catch (SQLException ex1) {
                    Logger.getLogger(Login.class.getName()).log(Level.FINE, null, ex1);
                }

            } catch (HeadlessException | NumberFormatException e) {
                // @@ - show errors on Login Window
                L_Error_Login.setText(e.toString());
                L_Error_Login.setVisible(true);
                
                // @shree - handling too many session error by killing conn
                 try {
                    conn.close();
                } catch (SQLException ex1) {
                    Logger.getLogger(Login.class.getName()).log(Level.FINE, null, ex1);
                }
            }
        }
    }                                             

    private void B_Cancel_LoginActionPerformed(java.awt.event.ActionEvent evt) {                                               
        System.exit(0);
    }                                              

    private void formComponentShown(java.awt.event.ComponentEvent evt) {                                    

        // @@ - resetting the login window
        T_Username.setText("");
        T_Password.setText("");
        L_Error_Login.setVisible(false);

    }                                   

    private void T_UsernameFocusGained(java.awt.event.FocusEvent evt) {                                       

        // @@ - resetting the login window
        L_Error_Login.setVisible(false);
    }                                      

    private void T_PasswordFocusGained(java.awt.event.FocusEvent evt) {                                       

        // @@ - resetting the login window, clearing the previous password
        T_Password.setText("");
        L_Error_Login.setVisible(false);
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton B_Cancel_Login;
    private javax.swing.JButton B_Login_Login;
    private javax.swing.JLabel L_Error_Login;
    private javax.swing.JPanel P_Login;
    private javax.swing.JPasswordField T_Password;
    private javax.swing.JTextField T_Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration                   
}
