/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minipods;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

import java.sql.*;
import oracle.jdbc.*;
import java.math.*;
import java.io.*;
import java.awt.*;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.pool.OracleDataSource;

/**
 *
 * @author shree
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RBG_Students = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Tabs = new javax.swing.JTabbedPane();
        Tab_Students = new javax.swing.JPanel();
        P_ManageStudents = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        P_Button_Students = new javax.swing.JPanel();
        B_ShowAllStudents = new javax.swing.JButton();
        B_AddNewStudent = new javax.swing.JButton();
        B_FindStudent = new javax.swing.JButton();
        B_DeleteStudent = new javax.swing.JButton();
        B_ExitStudent = new javax.swing.JButton();
        LP_Students = new javax.swing.JLayeredPane();
        P_ShowAllStudents = new javax.swing.JPanel();
        L_Message_ShowAllStudent = new javax.swing.JLabel();
        P_Table_ShowAllStudents = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBL_ShowAllStudents = new javax.swing.JTable();
        P_AddNewStudent = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        L_Message_AddNewStudent = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        T_FirstName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        T_LastName = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        T_GPA = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        T_Email = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        RB_Freshman = new javax.swing.JRadioButton();
        RB_Sophomore = new javax.swing.JRadioButton();
        RB_Junior = new javax.swing.JRadioButton();
        RB_Senior = new javax.swing.JRadioButton();
        RB_Graduate = new javax.swing.JRadioButton();
        B_Add_AddNewStudent = new javax.swing.JButton();
        B_Cancel_AddNewStudent = new javax.swing.JButton();
        L_Error_AddNewStudent = new javax.swing.JLabel();
        P_FindStudent = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        T_FirstName1 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        B_Add_AddNewStudent1 = new javax.swing.JButton();
        B_Add_AddNewStudent2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MiniPods");
        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        setLocation(new java.awt.Point(100, 50));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel1.setText("MiniPods");

        Tabs.setBackground(new java.awt.Color(204, 204, 204));
        Tabs.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N

        Tab_Students.setBackground(new java.awt.Color(255, 255, 255));
        Tab_Students.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        P_ManageStudents.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel2.setText("Manage Students");

        P_Button_Students.setBackground(new java.awt.Color(0, 153, 153));
        P_Button_Students.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        B_ShowAllStudents.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        B_ShowAllStudents.setForeground(new java.awt.Color(0, 102, 102));
        B_ShowAllStudents.setText("Show All Students");
        B_ShowAllStudents.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_ShowAllStudents.setOpaque(false);
        B_ShowAllStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ShowAllStudentsActionPerformed(evt);
            }
        });

        B_AddNewStudent.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        B_AddNewStudent.setForeground(new java.awt.Color(0, 102, 102));
        B_AddNewStudent.setText("Add New Student");
        B_AddNewStudent.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_AddNewStudent.setOpaque(false);
        B_AddNewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_AddNewStudentActionPerformed(evt);
            }
        });

        B_FindStudent.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        B_FindStudent.setForeground(new java.awt.Color(0, 102, 102));
        B_FindStudent.setText("Find Student");
        B_FindStudent.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_FindStudent.setOpaque(false);
        B_FindStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_FindStudentActionPerformed(evt);
            }
        });

        B_DeleteStudent.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        B_DeleteStudent.setForeground(new java.awt.Color(0, 102, 102));
        B_DeleteStudent.setText("Delete Student");
        B_DeleteStudent.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_DeleteStudent.setOpaque(false);
        B_DeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_DeleteStudentActionPerformed(evt);
            }
        });

        B_ExitStudent.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        B_ExitStudent.setForeground(new java.awt.Color(0, 102, 102));
        B_ExitStudent.setText("Exit");
        B_ExitStudent.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_ExitStudent.setOpaque(false);

        javax.swing.GroupLayout P_Button_StudentsLayout = new javax.swing.GroupLayout(P_Button_Students);
        P_Button_Students.setLayout(P_Button_StudentsLayout);
        P_Button_StudentsLayout.setHorizontalGroup(
            P_Button_StudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_Button_StudentsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(P_Button_StudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(B_ExitStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_DeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_FindStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_AddNewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_ShowAllStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        P_Button_StudentsLayout.setVerticalGroup(
            P_Button_StudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_Button_StudentsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(B_ShowAllStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(B_AddNewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(B_FindStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(B_DeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 350, Short.MAX_VALUE)
                .addComponent(B_ExitStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        LP_Students.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        P_ShowAllStudents.setBackground(new java.awt.Color(204, 255, 204));
        P_ShowAllStudents.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        L_Message_ShowAllStudent.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        L_Message_ShowAllStudent.setText("Displaying all available students - ");

        P_Table_ShowAllStudents.setBackground(new java.awt.Color(204, 255, 204));
        P_Table_ShowAllStudents.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TBL_ShowAllStudents.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        TBL_ShowAllStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "sid", "firstname", "lastname", "status", "gpa", "email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBL_ShowAllStudents.setRowHeight(22);
        TBL_ShowAllStudents.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TBL_ShowAllStudents);
        if (TBL_ShowAllStudents.getColumnModel().getColumnCount() > 0) {
            TBL_ShowAllStudents.getColumnModel().getColumn(0).setResizable(false);
            TBL_ShowAllStudents.getColumnModel().getColumn(1).setResizable(false);
            TBL_ShowAllStudents.getColumnModel().getColumn(2).setResizable(false);
            TBL_ShowAllStudents.getColumnModel().getColumn(3).setResizable(false);
            TBL_ShowAllStudents.getColumnModel().getColumn(4).setResizable(false);
            TBL_ShowAllStudents.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout P_Table_ShowAllStudentsLayout = new javax.swing.GroupLayout(P_Table_ShowAllStudents);
        P_Table_ShowAllStudents.setLayout(P_Table_ShowAllStudentsLayout);
        P_Table_ShowAllStudentsLayout.setHorizontalGroup(
            P_Table_ShowAllStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        P_Table_ShowAllStudentsLayout.setVerticalGroup(
            P_Table_ShowAllStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout P_ShowAllStudentsLayout = new javax.swing.GroupLayout(P_ShowAllStudents);
        P_ShowAllStudents.setLayout(P_ShowAllStudentsLayout);
        P_ShowAllStudentsLayout.setHorizontalGroup(
            P_ShowAllStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_ShowAllStudentsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(P_ShowAllStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(P_Table_ShowAllStudents, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(P_ShowAllStudentsLayout.createSequentialGroup()
                        .addComponent(L_Message_ShowAllStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 1340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        P_ShowAllStudentsLayout.setVerticalGroup(
            P_ShowAllStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_ShowAllStudentsLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(L_Message_ShowAllStudent)
                .addGap(18, 18, 18)
                .addComponent(P_Table_ShowAllStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        P_AddNewStudent.setBackground(new java.awt.Color(153, 204, 255));
        P_AddNewStudent.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel3.setText("Please provide below details for the new student - ");

        L_Message_AddNewStudent.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        L_Message_AddNewStudent.setText("Congratulations!! Student added. Your B-Number (sid) is - ");

        jPanel5.setBackground(new java.awt.Color(153, 204, 255));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel4.setText("Firstname - ");

        T_FirstName.setBackground(new java.awt.Color(153, 204, 255));
        T_FirstName.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        T_FirstName.setText("Enter firstname here");
        T_FirstName.setBorder(null);
        T_FirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                T_FirstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                T_FirstNameFocusLost(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel6.setText("Lastname - ");

        T_LastName.setBackground(new java.awt.Color(153, 204, 255));
        T_LastName.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        T_LastName.setText("Enter lastname here");
        T_LastName.setBorder(null);
        T_LastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                T_LastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                T_LastNameFocusLost(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel5.setText("GPA -");

        T_GPA.setBackground(new java.awt.Color(153, 204, 255));
        T_GPA.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        T_GPA.setText("Enter gpa here");
        T_GPA.setBorder(null);
        T_GPA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                T_GPAFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                T_GPAFocusLost(evt);
            }
        });
        T_GPA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                T_GPAKeyTyped(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel7.setText("Email -");

        T_Email.setBackground(new java.awt.Color(153, 204, 255));
        T_Email.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        T_Email.setText("Enter email id here");
        T_Email.setBorder(null);
        T_Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                T_EmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                T_EmailFocusLost(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel8.setText("Status - ");

        RB_Freshman.setBackground(new java.awt.Color(153, 204, 255));
        RBG_Students.add(RB_Freshman);
        RB_Freshman.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        RB_Freshman.setText("Freshman");

        RB_Sophomore.setBackground(new java.awt.Color(153, 204, 255));
        RBG_Students.add(RB_Sophomore);
        RB_Sophomore.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        RB_Sophomore.setText("Sophomore");

        RB_Junior.setBackground(new java.awt.Color(153, 204, 255));
        RBG_Students.add(RB_Junior);
        RB_Junior.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        RB_Junior.setText("Junior");

        RB_Senior.setBackground(new java.awt.Color(153, 204, 255));
        RBG_Students.add(RB_Senior);
        RB_Senior.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        RB_Senior.setText("Senior");

        RB_Graduate.setBackground(new java.awt.Color(153, 204, 255));
        RBG_Students.add(RB_Graduate);
        RB_Graduate.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        RB_Graduate.setText("Graduate");

        B_Add_AddNewStudent.setFont(new java.awt.Font("Montserrat", 1, 15)); // NOI18N
        B_Add_AddNewStudent.setForeground(new java.awt.Color(0, 102, 102));
        B_Add_AddNewStudent.setText("Add");
        B_Add_AddNewStudent.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_Add_AddNewStudent.setOpaque(false);
        B_Add_AddNewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_Add_AddNewStudentActionPerformed(evt);
            }
        });

        B_Cancel_AddNewStudent.setFont(new java.awt.Font("Montserrat", 1, 15)); // NOI18N
        B_Cancel_AddNewStudent.setForeground(new java.awt.Color(0, 102, 102));
        B_Cancel_AddNewStudent.setText("Cancel");
        B_Cancel_AddNewStudent.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_Cancel_AddNewStudent.setOpaque(false);
        B_Cancel_AddNewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_Cancel_AddNewStudentActionPerformed(evt);
            }
        });

        L_Error_AddNewStudent.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        L_Error_AddNewStudent.setForeground(new java.awt.Color(255, 0, 51));
        L_Error_AddNewStudent.setText("Error goes here..!!");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(T_FirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
                        .addGap(192, 192, 192)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator3)
                            .addComponent(T_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(T_GPA, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator4)
                                    .addComponent(T_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(RB_Freshman, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RB_Sophomore, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RB_Junior, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RB_Senior, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RB_Graduate, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(L_Error_AddNewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(255, 255, 255))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(B_Add_AddNewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(1060, Short.MAX_VALUE)
                    .addComponent(B_Cancel_AddNewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(21, 21, 21)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(T_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(T_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(T_GPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(T_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(RB_Freshman, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RB_Sophomore, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RB_Junior, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RB_Senior, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RB_Graduate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_Add_AddNewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_Error_AddNewStudent))
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(297, Short.MAX_VALUE)
                    .addComponent(B_Cancel_AddNewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(14, 14, 14)))
        );

        javax.swing.GroupLayout P_AddNewStudentLayout = new javax.swing.GroupLayout(P_AddNewStudent);
        P_AddNewStudent.setLayout(P_AddNewStudentLayout);
        P_AddNewStudentLayout.setHorizontalGroup(
            P_AddNewStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_AddNewStudentLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_AddNewStudentLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(P_AddNewStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(L_Message_AddNewStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59))
        );
        P_AddNewStudentLayout.setVerticalGroup(
            P_AddNewStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_AddNewStudentLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(L_Message_AddNewStudent)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        P_FindStudent.setBackground(new java.awt.Color(0, 204, 204));
        P_FindStudent.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel10.setText("Please provide student's B-Number (sid) - ");

        jPanel6.setBackground(new java.awt.Color(0, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "  Student Details - ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 0, 14))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 152, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(0, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "  Class Details -  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 0, 14))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        T_FirstName1.setBackground(new java.awt.Color(0, 204, 204));
        T_FirstName1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        T_FirstName1.setText("Enter (B-Number) sid here");
        T_FirstName1.setBorder(null);
        T_FirstName1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                T_FirstName1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                T_FirstName1FocusLost(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

        B_Add_AddNewStudent1.setFont(new java.awt.Font("Montserrat", 1, 15)); // NOI18N
        B_Add_AddNewStudent1.setForeground(new java.awt.Color(0, 102, 102));
        B_Add_AddNewStudent1.setText("Cancel");
        B_Add_AddNewStudent1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_Add_AddNewStudent1.setOpaque(false);
        B_Add_AddNewStudent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_Add_AddNewStudent1ActionPerformed(evt);
            }
        });

        B_Add_AddNewStudent2.setFont(new java.awt.Font("Montserrat", 1, 15)); // NOI18N
        B_Add_AddNewStudent2.setForeground(new java.awt.Color(0, 102, 102));
        B_Add_AddNewStudent2.setText("Find");
        B_Add_AddNewStudent2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_Add_AddNewStudent2.setOpaque(false);
        B_Add_AddNewStudent2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_Add_AddNewStudent2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout P_FindStudentLayout = new javax.swing.GroupLayout(P_FindStudent);
        P_FindStudent.setLayout(P_FindStudentLayout);
        P_FindStudentLayout.setHorizontalGroup(
            P_FindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_FindStudentLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(P_FindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_FindStudentLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(P_FindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator5)
                            .addComponent(T_FirstName1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 436, Short.MAX_VALUE)
                        .addComponent(B_Add_AddNewStudent2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(B_Add_AddNewStudent1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        P_FindStudentLayout.setVerticalGroup(
            P_FindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_FindStudentLayout.createSequentialGroup()
                .addGroup(P_FindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_FindStudentLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(P_FindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(P_FindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(T_FirstName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(P_FindStudentLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(P_FindStudentLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(P_FindStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B_Add_AddNewStudent1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_Add_AddNewStudent2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        LP_Students.setLayer(P_ShowAllStudents, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LP_Students.setLayer(P_AddNewStudent, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LP_Students.setLayer(P_FindStudent, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout LP_StudentsLayout = new javax.swing.GroupLayout(LP_Students);
        LP_Students.setLayout(LP_StudentsLayout);
        LP_StudentsLayout.setHorizontalGroup(
            LP_StudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1388, Short.MAX_VALUE)
            .addGroup(LP_StudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(P_AddNewStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(LP_StudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(P_FindStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(LP_StudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(P_ShowAllStudents, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LP_StudentsLayout.setVerticalGroup(
            LP_StudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
            .addGroup(LP_StudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(P_AddNewStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(LP_StudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(P_FindStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(LP_StudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(P_ShowAllStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout P_ManageStudentsLayout = new javax.swing.GroupLayout(P_ManageStudents);
        P_ManageStudents.setLayout(P_ManageStudentsLayout);
        P_ManageStudentsLayout.setHorizontalGroup(
            P_ManageStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_ManageStudentsLayout.createSequentialGroup()
                .addGap(753, 753, 753)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(P_ManageStudentsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(P_Button_Students, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LP_Students)
                .addContainerGap())
        );
        P_ManageStudentsLayout.setVerticalGroup(
            P_ManageStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_ManageStudentsLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(P_ManageStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(P_Button_Students, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LP_Students))
                .addContainerGap())
        );

        javax.swing.GroupLayout Tab_StudentsLayout = new javax.swing.GroupLayout(Tab_Students);
        Tab_Students.setLayout(Tab_StudentsLayout);
        Tab_StudentsLayout.setHorizontalGroup(
            Tab_StudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_ManageStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Tab_StudentsLayout.setVerticalGroup(
            Tab_StudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_ManageStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Tabs.addTab("   Manage Students   ", Tab_Students);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1703, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
        );

        Tabs.addTab("   View Courses   ", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1703, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
        );

        Tabs.addTab("   View Classes   ", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1703, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
        );

        Tabs.addTab("   Manage Enrollments   ", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1703, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
        );

        Tabs.addTab("   View Logs   ", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tabs)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(784, 784, 784))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // @shree - Show all student
    private void B_ShowAllStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ShowAllStudentsActionPerformed

        // @shree - show P_ShowAllStudents panel, hide all others
        P_ShowAllStudents.setVisible(true);
        P_AddNewStudent.setVisible(false);
        P_FindStudent.setVisible(false);
        //P_DeleteStudent.setVisible(false);

        // @shree - fecthing the data using procedure and display on GUI
        try {

            // @shree - connect to DB
            OracleDataSource ds = new oracle.jdbc.pool.OracleDataSource();
            ds.setURL("jdbc:oracle:thin:@localhost:1521:orcl");
            Connection conn = ds.getConnection("shree", "shree2103");

            // @shree - fetching result from DB usnig procedure
            CallableStatement call = conn.prepareCall("begin SQLPackage.display_students(?); end;");
            call.registerOutParameter(1, OracleTypes.CURSOR);
            call.execute();

            ResultSet rs = (ResultSet) call.getObject(1);

            
            
            // @shree - inserting data into the table on GUI
            DefaultTableModel model = (DefaultTableModel) TBL_ShowAllStudents.getModel();
            model.setRowCount(0);
            TBL_ShowAllStudents.setModel(model);
            
            int cols = TBL_ShowAllStudents.getColumnCount();

            while (rs.next()) {
                Object[] obj = new Object[cols];
                for (int i = 0; i < cols; i++) {
                    obj[i] = rs.getObject(i + 1);
                }
                model.addRow(obj);
            }

            L_Message_ShowAllStudent.setText("Displaying all available students - ");
            L_Message_ShowAllStudent.setForeground(Color.BLACK);
            TBL_ShowAllStudents.setModel(model);
            TBL_ShowAllStudents.getTableHeader().setFont(new Font("Monteserrat", Font.BOLD, 14));

            conn.close();

        } catch (SQLException ex) {
            L_Message_ShowAllStudent.setText("SQL Exception : " + ex);
            L_Message_ShowAllStudent.setForeground(Color.RED);
        } catch (Exception e) {
            L_Message_ShowAllStudent.setText("Exception : " + e);
            L_Message_ShowAllStudent.setForeground(Color.RED);
        }
    }//GEN-LAST:event_B_ShowAllStudentsActionPerformed

    // @shree - Add new student - show panel for adding new student
    private void B_AddNewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_AddNewStudentActionPerformed

        // @shree - show P_AddNewStudents panel, hide all others
        P_ShowAllStudents.setVisible(false);
        P_AddNewStudent.setVisible(true);
        P_FindStudent.setVisible(false);
        //     P_DeleteStudent.setVisible(false);

        // @shree - resetting the panel (textbox values, selections etc.)
        L_Error_AddNewStudent.setVisible(false);
        L_Message_AddNewStudent.setVisible(false);
        T_FirstName.setText("Enter firstname here");
        T_LastName.setText("Enter lastname here");
        T_GPA.setText("Enter gpa here");
        T_Email.setText("Enter email id here");
        RBG_Students.clearSelection();

    }//GEN-LAST:event_B_AddNewStudentActionPerformed

    // @shree - Add students to DB
    private void B_Add_AddNewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_Add_AddNewStudentActionPerformed

        // @shree - Performing validation on the details provided
        if (T_FirstName.getText().equals("") || T_FirstName.getText().equals("Enter firstname here")) {
            L_Error_AddNewStudent.setText("Please provide valid firstname!");
            L_Error_AddNewStudent.setVisible(true);

        } else if (T_LastName.getText().equals("") || T_LastName.getText().equals("Enter lastname here")) {
            L_Error_AddNewStudent.setText("Please provide valid lastname!");
            L_Error_AddNewStudent.setVisible(true);

        } else if ((!(T_GPA.getText().equals("") || T_GPA.getText().equals("Enter gpa here"))) && (Float.parseFloat(T_GPA.getText()) < 0 || Float.parseFloat(T_GPA.getText()) > 4.0)) {
            L_Error_AddNewStudent.setText("Please provide valid gpa!");
            L_Error_AddNewStudent.setVisible(true);

        } else if (T_Email.getText().equals("") || T_Email.getText().equals("Enter email id here") || (!T_Email.getText().contains("@"))) {
            L_Error_AddNewStudent.setText("Please provide valid email id!");
            L_Error_AddNewStudent.setVisible(true);

        } else if (RB_Freshman.isSelected() == false && RB_Sophomore.isSelected() == false && RB_Junior.isSelected() == false && RB_Senior.isSelected() == false && RB_Graduate.isSelected() == false) {
            L_Error_AddNewStudent.setText("Please select valid status!");
            L_Error_AddNewStudent.setVisible(true);

        } else {

            L_Error_AddNewStudent.setVisible(false);

            // @shree - generate sid
            try {

                int SID = 0;
                String sid = "B";

                // @shree - connect to DB
                OracleDataSource ds = new oracle.jdbc.pool.OracleDataSource();
                ds.setURL("jdbc:oracle:thin:@localhost:1521:orcl");
                Connection conn = ds.getConnection("shree", "shree2103");

                Statement stmt = conn.createStatement();

                ResultSet rs;
                rs = stmt.executeQuery("SELECT MAX(sid) FROM students");

                while (rs.next()) {
                    SID = Integer.parseInt(rs.getString(1).substring(1));
                }

                // @shree - sid reached to 999, then do nothing
                if (SID >= 999) {
                    L_Error_AddNewStudent.setText("Maximum SID (999) reached!");
                    L_Error_AddNewStudent.setVisible(true);
                } else {

                    SID++;

                    if (SID < 10) {
                        sid = sid + "00" + SID;
                    } else if (SID < 99) {
                        sid = sid + "0" + SID;
                    } else if (SID < 999) {
                        sid = sid + SID;
                    }

                    // @shree - getting the student's details from the GUI
                    String firstname = T_FirstName.getText();
                    String lastname = T_LastName.getText();
                    String email = T_Email.getText();
                    String status = "";

                    if (RB_Freshman.isSelected()) {
                        status = "freshman";
                    } else if (RB_Sophomore.isSelected()) {
                        status = "sophomore";
                    } else if (RB_Junior.isSelected()) {
                        status = "junior";
                    } else if (RB_Senior.isSelected()) {
                        status = "senior";
                    } else if (RB_Graduate.isSelected()) {
                        status = "graduate";
                    }

                    // @shree - calling procedure to add student
                    CallableStatement call = conn.prepareCall("begin SQLPackage.add_student(?, ?, ?, ?, ?, ?); end;");
                    call.setString(1, sid);
                    call.setString(2, firstname);
                    call.setString(3, lastname);
                    call.setString(4, status);
                    call.setString(6, email);

                    if (T_GPA.getText().equals("") || T_GPA.getText().equals("Enter gpa here")) {
                        call.setString(5, "");
                    } else {
                        Float gpa = Float.parseFloat(T_GPA.getText());
                        call.setFloat(5, gpa);
                    }

                    int temp = call.executeUpdate();

                    if (temp == 1) {
                        L_Message_AddNewStudent.setText("Congratulations!! Student added. Your B-Number (sid) is - " + sid);
                        L_Message_AddNewStudent.setForeground(Color.BLACK);
                        L_Message_AddNewStudent.setVisible(true);

                        T_FirstName.setText("Enter firstname here");
                        T_LastName.setText("Enter lastname here");
                        T_GPA.setText("Enter gpa here");
                        T_Email.setText("Enter email id here");
                        RBG_Students.clearSelection();
                    }
                }

                conn.close();

            } catch (SQLException ex) {

                if (ex.toString().contains("java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constrain")) {
                    L_Error_AddNewStudent.setText("SQL Exception : Email id should be unique!");
                    L_Error_AddNewStudent.setVisible(true);
                } else {
                    L_Message_AddNewStudent.setText("SQL Exception : " + ex);
                    L_Message_AddNewStudent.setForeground(Color.RED);
                    L_Message_AddNewStudent.setVisible(true);
                }
                
            } catch (HeadlessException | NumberFormatException e) {
                L_Message_AddNewStudent.setText("Exception : " + e);
                L_Message_AddNewStudent.setForeground(Color.RED);
                L_Message_AddNewStudent.setVisible(true);
            }
        }
    }//GEN-LAST:event_B_Add_AddNewStudentActionPerformed

    //@shree - Cancel adding new student
    private void B_Cancel_AddNewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_Cancel_AddNewStudentActionPerformed

    }//GEN-LAST:event_B_Cancel_AddNewStudentActionPerformed

    // @shree - Find student
    private void B_FindStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_FindStudentActionPerformed

        // @shree - show P_FindStudent panel, hide all others
        P_ShowAllStudents.setVisible(false);
        P_AddNewStudent.setVisible(false);
        P_FindStudent.setVisible(true);
        //P_DeleteStudent.setVisible(false);
    }//GEN-LAST:event_B_FindStudentActionPerformed

    // @shree - Delete student
    private void B_DeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_DeleteStudentActionPerformed

        // @shree - show P_DeleteStudent panel, hide all others
        P_ShowAllStudents.setVisible(false);
        P_AddNewStudent.setVisible(false);
        P_FindStudent.setVisible(false);
        //P_DeleteStudent.setVisible(true);
    }//GEN-LAST:event_B_DeleteStudentActionPerformed

    // @shree - Focus gained by firstname textbox
    private void T_FirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_T_FirstNameFocusGained

        // @shree - clearing the default text on focus
        if (T_FirstName.getText().equals("Enter firstname here")) {
            T_FirstName.setText("");

        }
        L_Error_AddNewStudent.setVisible(false);
        L_Message_AddNewStudent.setVisible(false);
    }//GEN-LAST:event_T_FirstNameFocusGained

    // @shree - Foucs lost by firstname textbox
    private void T_FirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_T_FirstNameFocusLost

        // @shree - resetting the defualt text if the firstname is not entered
        if (T_FirstName.getText().equals("")) {
            T_FirstName.setText("Enter firstname here");
        }
    }//GEN-LAST:event_T_FirstNameFocusLost

    // @shree - Focus gained by lastname textbox
    private void T_LastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_T_LastNameFocusGained

        // @shree - clearing the default text on focus
        if (T_LastName.getText().equals("Enter lastname here")) {
            T_LastName.setText("");

        }
        L_Error_AddNewStudent.setVisible(false);
        L_Message_AddNewStudent.setVisible(false);
    }//GEN-LAST:event_T_LastNameFocusGained

    // @shree - Focus lost by lastname textbox
    private void T_LastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_T_LastNameFocusLost

        // @shree - resetting the defualt text if the lastname is not entered
        if (T_LastName.getText().equals("")) {
            T_LastName.setText("Enter lastname here");
        }
    }//GEN-LAST:event_T_LastNameFocusLost

    // @shree - Focus gained by GPA textbox
    private void T_GPAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_T_GPAFocusGained

        // @shree - clearing the default text on focus
        if (T_GPA.getText().equals("Enter gpa here")) {
            T_GPA.setText("");

        }
        L_Error_AddNewStudent.setVisible(false);
        L_Message_AddNewStudent.setVisible(false);
    }//GEN-LAST:event_T_GPAFocusGained

    // @shree - Focus lost by GPA textbox
    private void T_GPAFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_T_GPAFocusLost

        // @shree - resetting the defualt text if the gpa is not entered
        if (T_GPA.getText().equals("")) {
            T_GPA.setText("Enter gpa here");
        }
    }//GEN-LAST:event_T_GPAFocusLost

    // @shree - Focus gained by email textbox
    private void T_EmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_T_EmailFocusGained

        // @shree - clearing the default text on focus
        if (T_Email.getText().equals("Enter email id here")) {
            T_Email.setText("");
        }
        L_Error_AddNewStudent.setVisible(false);
        L_Message_AddNewStudent.setVisible(false);
    }//GEN-LAST:event_T_EmailFocusGained

    // @shree - Focus lost by email textbox
    private void T_EmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_T_EmailFocusLost

        // @shree - resetting the defualt text if the email is not entered
        if (T_Email.getText().equals("")) {
            T_Email.setText("Enter email id here");
        }
    }//GEN-LAST:event_T_EmailFocusLost

    // @shree - GPA input restrictions
    private void T_GPAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_T_GPAKeyTyped

        // @shree - allowing only numbers and .
        char temp = evt.getKeyChar();

        if (Character.isDigit(temp) || temp == KeyEvent.VK_PERIOD) {

            if (temp == KeyEvent.VK_PERIOD && T_GPA.getText().contains(".")) {
                evt.consume();
            }

        } else {
            evt.consume();
        }
    }//GEN-LAST:event_T_GPAKeyTyped

    private void T_FirstName1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_T_FirstName1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_T_FirstName1FocusGained

    private void T_FirstName1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_T_FirstName1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_T_FirstName1FocusLost

    private void B_Add_AddNewStudent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_Add_AddNewStudent1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_Add_AddNewStudent1ActionPerformed

    private void B_Add_AddNewStudent2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_Add_AddNewStudent2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_Add_AddNewStudent2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_AddNewStudent;
    private javax.swing.JButton B_Add_AddNewStudent;
    private javax.swing.JButton B_Add_AddNewStudent1;
    private javax.swing.JButton B_Add_AddNewStudent2;
    private javax.swing.JButton B_Cancel_AddNewStudent;
    private javax.swing.JButton B_DeleteStudent;
    private javax.swing.JButton B_ExitStudent;
    private javax.swing.JButton B_FindStudent;
    private javax.swing.JButton B_ShowAllStudents;
    private javax.swing.JLayeredPane LP_Students;
    private javax.swing.JLabel L_Error_AddNewStudent;
    private javax.swing.JLabel L_Message_AddNewStudent;
    private javax.swing.JLabel L_Message_ShowAllStudent;
    private javax.swing.JPanel P_AddNewStudent;
    private javax.swing.JPanel P_Button_Students;
    private javax.swing.JPanel P_FindStudent;
    private javax.swing.JPanel P_ManageStudents;
    private javax.swing.JPanel P_ShowAllStudents;
    private javax.swing.JPanel P_Table_ShowAllStudents;
    private javax.swing.ButtonGroup RBG_Students;
    private javax.swing.JRadioButton RB_Freshman;
    private javax.swing.JRadioButton RB_Graduate;
    private javax.swing.JRadioButton RB_Junior;
    private javax.swing.JRadioButton RB_Senior;
    private javax.swing.JRadioButton RB_Sophomore;
    private javax.swing.JTable TBL_ShowAllStudents;
    private javax.swing.JTextField T_Email;
    private javax.swing.JTextField T_FirstName;
    private javax.swing.JTextField T_FirstName1;
    private javax.swing.JTextField T_GPA;
    private javax.swing.JTextField T_LastName;
    private javax.swing.JPanel Tab_Students;
    private javax.swing.JTabbedPane Tabs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
